#!/bin/bash

sudo apt install -y git vim ctags tmux 

ret=$(echo "$?")

[ "$ret" = "0" ] || exit 1

git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.ss stash
git config --global alias.sl 'stash list'
git config --global alias.unstage 'reset HEAD --'
git config --global alias.last 'log -1 HEAD'

path_bash=$HOME/.bash
path_vim=$HOME/.vim

if [ ! -d $path_bash ]
then
    git clone http://github.com/yihsiu806/bash.git $HOME/.bash
fi
if [ ! -d $path_vim ]
then
    git clone http://github.com/yihsiu806/vim.git $HOME/.vim
fi

FILES="bashrc cdecd screenrc tmux.conf vimrc"
TIMESTAMP=$(date +%s)

for f in $FILES
do
    fpath=$HOME/.$f

    if [ -h "$fpath" -o -d "$fpath" ]
    then
        echo "Remove ${fpath} (`stat --format=%F ${fpath}`)"
        rm ${fpath}
    elif [ -f "$fpath" ]
    then
        read -p "Do you want to backup exist ${fpath} ? (y/N): " backup
        if [ "$backup" == "y" -o "$backup" == "Y" ]
        then
            new_fpath=${fpath}.bak.${TIMESTAMP}
            mv ${fpath} ${new_fpath}
            echo "Backup ${fpath} to ${new_fpath}"
        fi
    fi
done

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
for f in $FILES
do
    if [ $f = "vimrc" ]
    then
        continue
    fi
    fpath=$HOME/.bash/$f
    linkname=$HOME/.$f
    echo "Create symlink $linkname"
    ln -s $fpath $linkname
done

ln -s $HOME/.vim/vimrc $HOME/.vimrc